{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rhino
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rhino_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rhino/rhino_{{ version }}.tar.gz
  sha256: e272edbd9fd1b26f0cc08a1d296bf157780fbd93c08fb4cc356fe9406ff0b8fe

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-box
    - r-cli
    - r-config
    - r-fs
    - r-glue
    - r-lintr >=3.0.0
    - r-logger
    - r-purrr
    - r-renv
    - r-rstudioapi
    - r-sass
    - r-shiny
    - r-styler
    - r-testthat >=3.0.0
    - r-withr
    - r-yaml
  run:
    - r-base
    - r-box
    - r-cli
    - r-config
    - r-fs
    - r-glue
    - r-lintr >=3.0.0
    - r-logger
    - r-purrr
    - r-renv
    - r-rstudioapi
    - r-sass
    - r-shiny
    - r-styler
    - r-testthat >=3.0.0
    - r-withr
    - r-yaml

test:
  commands:
    - $R -e "library('rhino')"           # [not win]
    - "\"%R%\" -e \"library('rhino')\""  # [win]

about:
  home: https://appsilon.github.io/rhino/, https://github.com/Appsilon/rhino
  license: LGPL-3.0-only
  summary: A framework that supports creating and extending enterprise Shiny applications using best practices.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
