{% set version = "1.10.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rhino
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rhino_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rhino/rhino_{{ version }}.tar.gz
  sha256: 4e7f264f1cc3e02b8bb0cc7f52fa06fe858a51ef5fe87ce984104b583db18b96

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip             # [win]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
  host:
    - r-base
    - r-box >=1.1.3
    - r-box.linters >=0.9.1
    - r-cli
    - r-config
    - r-fs
    - r-glue
    - r-lintr >=3.0.0
    - r-logger
    - r-purrr
    - r-renv
    - r-rstudioapi
    - r-sass
    - r-shiny
    - r-styler
    - r-testthat >=3.0.0
    - r-withr
    - r-xml2
    - r-yaml
  run:
    - r-base
    - r-box >=1.1.3
    - r-box.linters >=0.9.1
    - r-cli
    - r-config
    - r-fs
    - r-glue
    - r-lintr >=3.0.0
    - r-logger
    - r-purrr
    - r-renv
    - r-rstudioapi
    - r-sass
    - r-shiny
    - r-styler
    - r-testthat >=3.0.0
    - r-withr
    - r-xml2
    - r-yaml

test:
  commands:
    - $R -e "library('rhino')"           # [not win]
    - "\"%R%\" -e \"library('rhino')\""  # [win]

about:
  home: https://appsilon.github.io/rhino/
  dev_url: https://github.com/Appsilon/rhino
  license: LGPL-3.0-only
  summary: A framework that supports creating and extending enterprise Shiny applications using best practices.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
